### ISSUE TITLE
Create Login and Register components

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/magic-read-FE#2]
**Code the login and register components for the app**

Refer to this [this](https://whimsical.com/Q3PdZoMzSLaSe5s3L26fE3) file and create the login and register components for the app using Material UI.

Make sure to pull the changes before you make any PR.

**Comment by najimali** [comment]
Hey Fab, I can make things work, please assign this issue to me.

**Comment by fabcodingzest** [comment]
sure @najimali , all the best!
