### ISSUE TITLE
Create Navbar and Footer components.

### ISSUE THREAD

**Issue by fabcodingzest** [Code-Dabblers/magic-read-FE#3]
**Code Navbar and Footer components for the app using material UI**

Refer to [this](https://whimsical.com/Q3PdZoMzSLaSe5s3L26fE3) file to have some idea of design.

**Comment by jigmetnamgyal** [comment]
Let me do this )

**Comment by fabcodingzest** [comment]
Sure @JigmeT123 
All the best!

**Comment by najimali** [comment]
Hey, please assign this task to me.
