### ISSUE TITLE
New story page

### ISSUE THREAD

**Issue by manangouhari** [Code-Dabblers/magic-read-FE#7]
The task is to implement a page where the user inputs a form for the details of creating a new story. 
Here's the wireframe(it's a rough idea, feel free to play around with the layout) - [wireframe](https://whimsical.com/Q3PdZoMzSLaSe5s3L26fE3@2Ux7TurymQGdd4hYYvij).

1. Make a new js file - `NewStory.js` under the `src/pages` folder. 
2. Go to `route.js` and add it as a new route  - `/new/story`.
3. Implement the UI.

No logic for form submission to the API is needed right now, only the UI needs to made.
Important - tags input is a multiselect.

**Comment by NadaaFarook** [comment]
I want to take up this issue.

**Comment by manangouhari** [comment]
Perfect, assigned the issue to you.
A reminder, you need to use Material-UI. 
In case you need a refresher or a tutorial on Material-UI - https://www.youtube.com/watch?v=vyJU9efvUtQ
