### ISSUE TITLE
Welcome component for user dashboard

### ISSUE THREAD

**Issue by manangouhari** [Code-Dabblers/magic-read-FE#8]
This is an isolated component that'll be used in the user dashboard.
To see it while development, simply output it to `pages/Home.js`.

Accepts these props - 
1. `username`
2. `numStoriesRead`
3. `numStoriesWritten`

"Start writing" button right now will be an empty link.

Suggestion - Use the `Paper` component from Material-UI as the base for this component.

![image](https://user-images.githubusercontent.com/31039184/95983183-d50b9780-0e3e-11eb-9e1e-7a3c98bc5694.png)

**Comment by najimali** [comment]
Hey please assign it to me.
